server:
  port: 10001
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/Bank
    username: postgres
    password: ${DB_PASSWORD:changeme}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      properties:
        spring.json.add.type.headers: false

