server:
  port: 10000
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Bank
    username: postgres
    password: waleed544
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: user_service
        ai:
          openai:
            api-key: sk-placeholder-not-real